name: tests

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python 3.12
        uses: actions/setup-python@v7.0.0
        with:
          python-version: 3.12

      - name: Install system deps
        shell: bash
        run: |
          pip install uv
          uv sync --extra dev --extra linters

      - name: Linting
        shell: bash
        run: uv run pre-commit run --all-files

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Console tests
        run: node --test tests/*.mjs

  tests:
    needs: linting
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [Ubuntu, MacOS]
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: true
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and Playwright Browsers
        shell: bash
        run: |
          pip install uv
          uv sync --python ${{ matrix.python-version }} --extra dev --extra test --extra typing
          uv run playwright install --with-deps

      - name: Run mypy
        shell: bash
        run: uv run inv mypy

      - name: Run tests
        shell: bash
        run: uv run inv tests
